### ISSUE TITLE
修改

### ISSUE THREAD

**Issue by yiminghe** [react-component/rate#1]
1. [x] 英文文档
2. [x] lint 通过 npm run lint
3. [x] initNum 属性改为 value
4. [x] 删除 import '../assets/index.less';
5. [x] 删除 onHover/onClick/disableHover/disableClick/useHover ，统一交互
6. [x] 删除 color,size 移到 css 指定
7. [x] half 改为 allowHalf, starNum 改为 count
8. [x] 从 className 删除 iconfont

**Comment by benjycui** [comment]
确认完毕，关闭
