### ISSUE TITLE
character api typescript ts(2322)

### ISSUE THREAD

**Issue by SomeBigPig** [react-component/rate#101]
![image](https://user-images.githubusercontent.com/34830983/99259626-403cf500-2855-11eb-81cb-3eb2c853fc35.png)

should character api be defined as ((props: StarProps) => React.ReactNode) | React.ReactNode ?

Otherwise when i give <Icon /> value to character, it throw ts error "不能将类型“Element”分配给类型“(props: StarProps) => ReactNode”。"

**Comment by xrkffgg** [comment]
`+rc-rate@2.9.1`
