### ISSUE TITLE
Fonts from alicdn used by rc-rate

### ISSUE THREAD

**Issue by mm-dsibinski** [react-component/rate#107]
Hi guys!
I'm using the `rc-rate` control in JS app. The app's webpack configuration outputs CSS from external libraries into a single .css file. However, there's a problem with fonts loaded from `alicdn` in rc-rate: https://github.com/react-component/rate/blob/61c976c109369955207391dbc5b9febe81a3470f/assets/index.less#L89

We can only use resources loaded from our local network because of security policy.
Do you have any idea how to replace this URL with local URL?
Thanks for your help ;)

**Comment by xrkffgg** [comment]
You can use your own new style instead of referring base style.

The new ones can refer to index.less and replace the @font-face

**Comment by mm-dsibinski** [comment]
Thanks @xrkffgg , this is what I did and it worked :)
