### ISSUE TITLE
should `allowHalf` take roundoff into consideration?

### ISSUE THREAD

**Issue by dickeylth** [react-component/rate#13]
For now, `allowHalf` only works with [exact `{x}.5` values](https://github.com/react-component/rate/blob/master/src/Star.jsx#L33) such as `1.5`, `2.5` and so on. If I pass value as `2.6` the result is same as `2`, which in my opinion is not the right output. I think either `2.5` or `3` should be the desired output instead of `2`, is that reasonable?

<https://codesandbox.io/s/vq87w5v025>

**Comment by NguyenTheSon** [comment]
same issue

**Comment by xrkffgg** [comment]
@afc163 

这边的 issues 我看一遍，能处理都处理一下。本来想等一起发版的。
😂😂  你太迅速了。
antd 月底才用到，我等这边处理完，再更新那边。

**Comment by afc163** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/507615/84485995-57d4e800-accf-11ea-83b1-b8e61ed322b0.png">
