### ISSUE TITLE
can't get the corret startValue if document or body has border width

### ISSUE THREAD

**Issue by YuanXingH** [react-component/rate#55]
the getOffsetLeft function in util.js calculates the distance from the element to the viewport minus body.clientLeft。If html or body has border width, then event.PageX minus leftDis can not get corrent value, then I can not get the half star.
```
  getStarValue(index, x) {
    const { allowHalf } = this.props;
    let value = index + 1;
    if (allowHalf) {
      const starEle = this.getStarDOM(index);
      // starEle.getBoundingClientRect().left - body.clientLeft
      const leftDis = getOffsetLeft(starEle);
      const width = starEle.clientWidth;
      if (x - leftDis < width / 2) {
        value -= 0.5;
      }
    }
    return value;
  }
```
like this 
![1579433189](https://user-images.githubusercontent.com/26616949/72680372-12cbd180-3af4-11ea-9493-88869304375a.jpg)

**Comment by xrkffgg** [comment]
It is not recommended to modify the body style.
