### ISSUE TITLE
Stars appear incorrectly due to fonts

### ISSUE THREAD

**Issue by whamtet** [react-component/rate#7]
The stars appear incorrectly in some browsers, for example

Chrome 58.0.3029.83 on Android 5.1.1

In this particular browser Noto Color Emoji font is being selected which breaks the appearance of the stars and prevents them from highlighting correctly.

![screenshot_2017-05-19-03-21-51](https://cloud.githubusercontent.com/assets/1909823/26221984/8959ed9a-3c42-11e7-93ab-3df12246bc56.png)

**Comment by whamtet** [comment]
Its not really a bug, probably just something we should point out in the documentation.  I can do a pull request if you'd like.

**Comment by xrkffgg** [comment]
PR welcome.

**Comment by whamtet** [comment]
Issue has disappeared on more recent browsers.  Will reopen if I see it again.
