### ISSUE TITLE
Styles not applying

### ISSUE THREAD

**Issue by luuiseb** [react-component/rate#89]
Im having an issue with the component where it doesnt apply the styles or something is happening... everything appears vertically and i didnt find anything on the docs.

Hope you can help me.

![image](https://user-images.githubusercontent.com/25963637/86989069-7c957180-c14e-11ea-9654-d51ea9f4f39d.png)

It shows like that and i've try everything i know.

Thank you in advance

**Comment by xrkffgg** [comment]
Can you provide a replay link? 
Or you can use developer tools to view its CSS

**Comment by MaryJJ** [comment]
Hi
I have the same problem.
![image](https://user-images.githubusercontent.com/46785613/87037472-442b7d00-c1ba-11ea-9e6f-cadf28af4610.png)

**Comment by xrkffgg** [comment]
@MaryJJ Can you provide a replay link?

**Comment by xrkffgg** [comment]
I've found it. Now fixing.

**Comment by xrkffgg** [comment]
Look Here: https://codesandbox.io/s/rc-rate-demo-p28eg?file=/index.js
